image: Visual Studio 2015

version: 1.0.{build}

branches:
    only:
        - master

environment:
    matrix:
        - QT: C:\Qt\5.7\msvc2015_64
          PLATFORM: amd64
          COMPILER: msvc
          VSVER: 14

clone_depth: 1

# scripts that run after cloning repository
install:
    - set PATH=%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;C:\Qt\QtIFW2.0.1\bin\;%PATH%
    - git submodule update --init --recursive

# scripts that run before build
before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
    - mkdir build
    - cd build
    - qmake -r -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release ../VNote.pro

# custom build scripts
build_script:
    - nmake

# scripts that run after build
after_build:
    - mkdir distrib\VNote
    - windeployqt.exe --dir .\distrib\VNote %APPVEYOR_BUILD_FOLDER%\build\src\release\VNote.exe
    - copy "%APPVEYOR_BUILD_FOLDER%\build\src\release\VNote.exe" "distrib\VNote\VNote.exe"
    - copy "%APPVEYOR_BUILD_FOLDER%\README.md" "distrib\VNote\README.md"
    - copy "%APPVEYOR_BUILD_FOLDER%\LICENSE" "distrib\VNote\LICENSE.txt"
    - echo %APPVEYOR_REPO_COMMIT% > "distrib\VNote\version.txt"
    - cd distrib
    - 7z a vnote_win_x86_64_portable_%APPVEYOR_BUILD_VERSION%.zip VNote

artifacts:
    - path: build\distrib\vnote_win_x86_64_portable_%APPVEYOR_BUILD_VERSION%.zip
      name: portable
